export const LORUM_IPSUM =
	'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fermentum nulla massa, sit amet pellentesque libero cursus id. Phasellus luctus dolor lacus, eu iaculis lectus ultricies eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam eu vulputate dui. Sed diam mi, fringilla ultricies efficitur eget, pulvinar vestibulum urna. Praesent scelerisque ligula sit amet metus sodales, quis egestas elit facilisis. Vestibulum ut odio orci. Donec risus quam, interdum et venenatis nec, cursus vitae justo. Proin massa dui, vulputate quis orci ac, fringilla efficitur augue. Ut aliquet nibh id ultricies scelerisque. Mauris vestibulum orci libero. Aliquam non nunc a leo feugiat mollis feugiat vitae sem.\n' +
	'\n' +
	'Aenean tempor libero neque, id semper neque blandit porta. Sed sit amet egestas massa, ac tempus ligula. Donec turpis justo, imperdiet sit amet luctus eget, commodo eget justo. Nullam nec tempor purus. Quisque ultricies leo ultrices ex faucibus, quis cursus mi cursus. Nullam eu urna libero. Nunc dictum eros sit amet congue aliquet. Aenean facilisis metus mi, at vehicula massa consectetur vel. Praesent nec nulla diam. Nam dignissim molestie ante, sit amet sodales libero placerat eu.\n' +
	'\n' +
	'Morbi maximus quis libero ac rutrum. Morbi sed elementum dolor. Vestibulum bibendum erat et leo molestie commodo. Quisque congue finibus odio. Pellentesque eu tincidunt ex, ut iaculis velit. Aliquam vestibulum at urna quis consectetur. Etiam eu nisi placerat ipsum laoreet lobortis. Aliquam ut diam mi. Vivamus tincidunt finibus odio mattis auctor. Vivamus porta laoreet commodo. Morbi auctor eros nunc, sed porta arcu ultrices eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tempor nec purus eget volutpat. Mauris posuere convallis metus sed faucibus. Nunc convallis aliquam nulla, a iaculis ex posuere ut. Aenean bibendum commodo tortor, nec porttitor est finibus vel.\n' +
	'\n' +
	'Mauris vestibulum gravida diam nec laoreet. Curabitur pharetra ipsum tortor. In hac habitasse platea dictumst. Aliquam scelerisque urna imperdiet nibh pulvinar malesuada et eget felis. Aliquam suscipit imperdiet tellus at suscipit. Nulla fermentum tellus id nisi mollis, vitae volutpat dolor venenatis. Aliquam erat volutpat. Proin aliquam lorem euismod ante ultrices, vel pulvinar turpis tristique. Vivamus efficitur purus ut porta vestibulum. Duis gravida a massa et porta.\n' +
	'\n' +
	'Nunc semper metus ac lectus lobortis fringilla et at magna. Donec at gravida ex. Nunc efficitur cursus sollicitudin. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent semper tempor mollis. Aliquam neque libero, molestie ut luctus nec, pulvinar quis orci. Nulla facilisi. Curabitur id orci elit. Nunc consequat gravida odio, a sagittis turpis condimentum ut. Aenean rutrum iaculis enim, at vulputate est congue quis. Fusce nec libero augue.'
